general {
    hide_cursor = false
}

background {
    color = rgba(000000ff)
}

input-field {
    size = 240, 50
    position = 0, -20
    monitor =
}

label {
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    position = 0, 40
    monitor =
}
