[General]
background=background.jpg
defaultBackground=background.jpg
backgroundColor=#0e1514
overlayColor=#cc0e1514
panelColor=#ff252b2b
fieldColor=#f00e1514
textColor=#dde4e3
mutedTextColor=#889392
accentColor=#80d5d2
accentTextColor=#003736
borderColor=#1a2120
font=Noto Sans
